#!/bin/bash
#setup
dir="libgsl0-dev_1.16+dfsg-1ubuntu1_amd64"
test_gsl=$(gsl-config --version 2>&1 | grep -o "command not found")
test_curl=$(curl --version 2>&1 | grep -o "command not found")
test_wget=$(wget --version 2>&1 | grep -o "command not found")
#commands
if [ "$test_wget" != "command not found" ]; then
  WGET="wget -O"
elif [ "$test_curl" != "command not found" ]; then
  WGET="curl -L --output"
fi
#setup working directory
mkdir -p ./ext-dep
#check for existing gsl
if [ "$test_gsl" == "command not found" ]; then
  mkdir -p ./lib/include/gsl
  cd ext-dep
  #download
  echo "downloading...gsl to $PWD"
  $WGET http://archive.ubuntu.com/ubuntu/pool/main/g/gsl/$dir.deb > /dev/null 2>&1
  #unpack
  echo "unpacking....."
  ar  -x $dir.deb
  tar -xf data.tar.xz 2>&1
  #install into ./lib
  echo "installing....to $PWD../lib"
  cp ./usr/lib/libgslcblas.a ../lib
  cp ./usr/lib/libgsl.a      ../lib
  cp ./usr/bin/gsl-config    ../lib
  cp -r ./usr/include/gsl/gsl*.h  ../lib/include/gsl
  #clean up
  mkdir gsl
  mv control.tar.gz  gsl 2> /dev/null
  mv debian-binary   gsl 2> /dev/null
  mv data.tar.xz     gsl 2> /dev/null
  mv libgsl0-dev_1.16+dfsg-1ubuntu1_amd64.deb  gsl 2> /dev/null
  mv usr             gsl 2> /dev/null
  cd ../ 2> /dev/null
  #adjust unpacked gsl-config to point to current location in ./lib
  sed -i "s/\/usr\/include/.\/lib\/include/"   ./lib/gsl-config
  sed -i "s/\/usr\//.\//"      ./lib/gsl-config
else
  echo "gsl found in $(gsl-config --prefix)"
  echo "creating link to gsl-config in $PWD/lib"
  #create sym link to existing gsl-config so that make finds it
  ln -sf  $(which gsl-config) ./lib/gsl-config

fi
echo "Done"
