#!/bin/bash
#SBATCH -p best
#SBATCH -n 1

cd $SLURM_SUBMIT_DIR


#============================ DO NOT CHANGE FROM HERE


cd EVOS/GGGG/MMMM/

date -d now +%s > stamp

cp -r ../../../INI/NNET/* .

./maise-nnet > out

mv POSCAR    POSCAR.0
mv CONTCAR   CONTCAR.0
mv OUTCAR    OUTCAR.0
mv OSZICAR   OSZICAR.0
mv PRIM      PRIM.0
mv CONV      CONV.0

rm -rf setup tmp* wyck* mod* maise-nnet
cd ../../..
